release v0.1.0
pjhartzell/raster-footprint pull request #28
Opened 2023-09-23 02:17 UTC by pjhartzell

## Description

Release v0.2.0

Added

- Added a CLI ([#27](https://github.com/pjhartzell/raster-footprint/issues/27))
- Added a `precision` option to the densify functions
  ([#25](https://github.com/pjhartzell/raster-footprint/issues/25))

Changed

- Changed default behavior in mask and footprint creation to not include holes
  ([#26](https://github.com/pjhartzell/raster-footprint/pull/26))
- Moved `geometry` argument to first position in `reproject_geometry`
  ([#24](https://github.com/pjhartzell/raster-footprint/pull/24))

## Checklist

- [ ] Add tests
- [ ] Add docs
- [x] Update CHANGELOG

2023-09-25 11:13 UTC, gadomski requested changes

2023-09-25 11:13 UTC, gadomski commented on CHANGELOG.md
> +[0.2.0]: https://github.com/pjhartzell/raster-footprint/releases/tag/v0.2.0
```suggestion
[0.2.0]: https://github.com/pjhartzell/raster-footprint/releases/compare/v0.1.0...v0.2.0
```

2023-09-25 11:13 UTC, gadomski approved these changes

2023-09-26 11:18 UTC, pjhartzell commented on CHANGELOG.md
> +[0.2.0]: https://github.com/pjhartzell/raster-footprint/releases/tag/v0.2.0
Good catch. Thanks!

2023-09-26 11:19 UTC, merged